branches:
  except:
    - gh-pages

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/python/bin:$PATH
    - NUPIC_STUDIO_DEPLOYMENT_BUILD=true

git:
  submodules: false

before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/before_install-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/install-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/install-osx.sh; fi"

script:
  # Check whether all dependencies were installed
  - "python -c 'import nupic;import numpy;from PyQt4 import Qt, QtGui, QtCore;import pyqtgraph;import pyqtgraph.opengl'"

  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/script-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/script-osx.sh; fi"
